### ISSUE TITLE
分类category页面bug

### ISSUE THREAD

**Issue by Colin-Jay** [dusign/dusign.github.io#1]
您好，感谢您的主题，让我有了自己的博客！
在使用您当前博客过程中，发现您虽然修复了主页categories不显示的bug，但是categories点进去却是archive的页面，由于我的技术不足，不能给您提更深层次的建议，所以很希望您能修复这个bug！
建议您在导航栏中也添加一个categories栏，像tags一样也有categories的页面！
另外，您的主题仓库希望可以更新一下：包括categories的bug以及Photography页面的最新请客^_^
这是我使用您的主题搭建的博客，https://colin-jay.cn/，目前主要就是困难categories的显示和Photography页面，希望可以从您这获得答案，我的联系方式wx：17718129575，很希望和您取得交流！

**Comment by dusign** [comment]
> 您好，感谢您的主题，让我有了自己的博客！
> 在使用您当前博客过程中，发现您虽然修复了主页categories不显示的bug，但是categories点进去却是archive的页面，由于我的技术不足，不能给您提更深层次的建议，所以很希望您能修复这个bug！
> 建议您在导航栏中也添加一个categories栏，像tags一样也有categories的页面！
> 另外，您的主题仓库希望可以更新一下：包括categories的bug以及Photography页面的最新请客^_^
> 这是我使用您的主题搭建的博客，[https://colin-jay.cn/，目前主要就是困难categories的显示和Photography页面，希望可以从您这获得答案，我的联系方式wx：17718129575，很希望和您取得交流！](https://colin-jay.cn/%EF%BC%8C%E7%9B%AE%E5%89%8D%E4%B8%BB%E8%A6%81%E5%B0%B1%E6%98%AF%E5%9B%B0%E9%9A%BEcategories%E7%9A%84%E6%98%BE%E7%A4%BA%E5%92%8CPhotography%E9%A1%B5%E9%9D%A2%EF%BC%8C%E5%B8%8C%E6%9C%9B%E5%8F%AF%E4%BB%A5%E4%BB%8E%E6%82%A8%E8%BF%99%E8%8E%B7%E5%BE%97%E7%AD%94%E6%A1%88%EF%BC%8C%E6%88%91%E7%9A%84%E8%81%94%E7%B3%BB%E6%96%B9%E5%BC%8Fwx%EF%BC%9A17718129575%EF%BC%8C%E5%BE%88%E5%B8%8C%E6%9C%9B%E5%92%8C%E6%82%A8%E5%8F%96%E5%BE%97%E4%BA%A4%E6%B5%81%EF%BC%81)

很高兴这个主题对你有帮助，Photography正在完善中，后期我会及时更新
